SRN: PES1UG20CS315

Data Analytics worksheet 5

Name: Purvik S Nukal

# PROBLEM 1

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
enc_arr = np.array([
    [0.002, 0.666, 0.31, 0, 0.022], [0.466, 0.102, 0.222, 0, 0.21], [0.022, 0.11, 0.502, 0, 0.366], [0, 0, 0, 1, 0], [0.11, 0.122, 0.066, 0, 0.702]
])
assert(enc_arr[0].sum() == 1.0)
assert(enc_arr[1].sum() == 1.0)
assert(enc_arr[2].sum() == 1.0)
assert(enc_arr[3].sum() == 1.0)
assert(enc_arr[4].sum() == 1.0)

initial_prob = np.array([[0.3, 0.4, 0.1, 0.15, 0.05]])
assert(initial_prob[0].sum() == 1.0)

In [ ]:
matrix_A=np.array([0.3,0.4,0.1,0.15,0.05])
matrix_B=np.array([
    [0.002, 0.666, 0.31, 0, 0.022], [0.466, 0.102, 0.222, 0, 0.21], [0.022, 0.11, 0.502, 0, 0.366], [0, 0, 0, 1, 0], [0.11, 0.122, 0.066, 0, 0.702]
])


In [ ]:
matrix_C=np.dot(matrix_A,matrix_B)
matrix_C

array([0.1947, 0.2577, 0.2353, 0.15  , 0.1623])

2) The Markov Chain can be reduced as from state 4, no other stae can be reached.

In [ ]:
#after 1 day
matrix_C=np.dot(matrix_A,matrix_B)
matrix_C

array([0.1947, 0.2577, 0.2353, 0.15  , 0.1623])

In [ ]:
#after 6 days
matrix_C = matrix_A
for i in range(6):
  matrix_C=np.dot(matrix_C,matrix_B)
matrix_C

array([0.12071648, 0.16375093, 0.20080912, 0.15      , 0.36472347])

In [ ]:
#after 1000 days
matrix_C=matrix_A
for i in range(1000):
  matrix_C=np.dot(matrix_C,matrix_B)
matrix_C

array([0.1214373 , 0.16411091, 0.19739717, 0.15      , 0.36705462])

In [ ]:
#after 1001 days
matrix_C=matrix_A
for i in range(1001):
  matrix_C=np.dot(matrix_C,matrix_B)
matrix_C

array([0.1214373 , 0.16411091, 0.19739717, 0.15      , 0.36705462])

4) We observe that the probabilities of a person going to a unit after 1000 days is equal to that after 1001 days, i.e it has reached steady state distribution.

---------------------------------------------------------------------------

# Problem 2

1) The chain is reducible as the 3rd and fourth chain cannot be reached.

In [ ]:
trans_array = np.array([
    [0.002, 0.666, 0.01, 0.020, 0.302], [0.466, 0.102, 0.02, 0.032, 0.38], [0.0, 0.0, 1, 0.0, 0.0], [0, 0, 0, 1, 0], [0.11, 0.122, 0.066, 0.004, 0.698]
])

assert(trans_array[0].sum() == 1.0)
assert(trans_array[1].sum() == 1.0)
assert(trans_array[2].sum() == 1.0)
assert(trans_array[3].sum() == 1.0)
assert(trans_array[4].sum() == 1.0)

state = np.array([[0.3, 0.4, 0.1, 0.15, 0.05]])
assert(state[0].sum() == 1.0)

In [ ]:
matrix_A = np.array([[0.3, 0.4, 0.1, 0.15, 0.05]])

matrix_B=np.array([
    [0.002, 0.666, 0.01, 0.020, 0.302], [0.466, 0.102, 0.02, 0.032, 0.38], [0.0, 0.0, 1, 0.0, 0.0], [0, 0, 0, 1, 0], [0.11, 0.122, 0.066, 0.004, 0.698]
])

In [ ]:
#after 1 day
matrix_C = np.dot(matrix_A,matrix_B)
matrix_C

array([[0.1925, 0.2467, 0.1143, 0.169 , 0.2775]])

In [ ]:
#after 6 days
matrix_C=matrix_A
for i in range(6):
  matrix_C=np.dot(matrix_C,matrix_B)
matrix_C

array([[0.0982811 , 0.12388067, 0.24785419, 0.21705012, 0.31293392]])

In [ ]:
#after 1000 days
matrix_C=matrix_A
for i in range(1000):
  matrix_C=np.dot(matrix_C,matrix_B)
matrix_C

array([[8.97378472e-28, 1.13004326e-27, 6.60595331e-01, 3.39404669e-01,
        2.87688168e-27]])

In [ ]:
#after 1001 days
matrix_C=matrix_A
for i in range(1001):
  matrix_C=np.dot(matrix_C,matrix_B)
matrix_C

array([[8.44851901e-28, 1.06389804e-27, 6.60595331e-01, 3.39404669e-01,
        2.70848815e-27]])

3) There is a difference in the probabilities of a person going to a unit after 1000 and 1001 days.

In [ ]:
a=np.array([[ 0 , 1 , 2 , 3], [ 4 , 5 , 6 , 7], [ 8,  9, 10, 11]])

In [ ]:
matrix_A = np.array([[0.3, 0.4, 0.1, 0.15, 0.05]])

matrix_B=np.array([
    [0.002, 0.666, 0.01, 0.020, 0.302], [0.466, 0.102, 0.02, 0.032, 0.38], [0.0, 0.0, 1, 0.0, 0.0], [0, 0, 0, 1, 0], 
    [0.11, 0.122, 0.066, 0.004, 0.698]
])

matrix_C = matrix_A @ matrix_B 
matrix_C

array([[0.1925, 0.2467, 0.1143, 0.169 , 0.2775]])

4) P(14)*P(Major crimes)

  = 0.02 x 0.3

  = 0.006

**PROBLEM 3**

In [ ]:
with_Amy = np.array([[0.002, 0.232, 0.31, 0.434, 0.022], [0.426, 0.102, 0.222, 0.04, 0.21], 
                     [0.03, 0.11, 0.20, 0.294, 0.366], [0.003, 0.176, 0.321, 0.3, 0.2], [0.11, 0.422, 0.166, 0.1, 0.202]])

without_Amy = np.array([[0.11, 0.222, 0.092, 0.374, 0.202], [0.03, 0.11, 0.20, 0.294, 0.366], [0.002, 0.232, 0.31, 0.434, 0.022], 
                        [0.466, 0.102, 0.02, 0.032, 0.38], [0.003, 0.176, 0.321, 0.3, 0.2]])

m_b = np.array([[0.3, 0.4, 0.1, 0.15, 0.05]])



1)To find new probabilities we calculate the first markov chain

In [ ]:
m_c = m_b@with_Amy
m_c

array([[0.17995, 0.1689 , 0.25825, 0.2256 , 0.1673 ]])

In [ ]:
m_c = m_b@without_Amy
m_c

array([[0.11525, 0.1579 , 0.15765, 0.293  , 0.2762 ]])

2) Santiago's presence caused a decrease in the feedback.

3) Captain Holt is performing the chi squared test

4) We can perform chi squared test on the transition matrix and find chi squared value and subsequent p-value to see if the transition matrix forms a Markov chain.